---
title: "PM 566 Midterm Project"
author: "Brandyn Ruiz"
date: "10/5/2020"
output: html_document
---

```{r, message=FALSE, echo=TRUE, warning=FALSE}
library(readr)
library(dplyr)
library(data.table)
library(httr)
library(rjson)
library(ggplot2)
library(usmap)
library(RColorBrewer)
library(rgdal)
library(ggrepel)
library(plotly)
```

## Introduction

## Methods

```{r Covid Github, message=FALSE, warning=FALSE}
download.file("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", "time_series_covid19_confirmed_US.csv", method="libcurl", timeout = 60)

covidGithub <- data.table::fread("time_series_covid19_confirmed_US.csv")

# Applying filter to only select covid confirmed cases in California
covidGithub <- covidGithub%>%
  filter(Province_State == 'California')%>%
  rename(county = Admin2)
```

```{r Covid Filter County}
# Table listing all counties within California
df <- unique(covidGithub$county)
knitr::kable(df, col.names = 'County')

covidGithub <- covidGithub[ !(covidGithub$county %in% c('Unassigned', 'Out of CA')), ]
```

```{r Melting Covid Data Set, message = FALSE, warning = FALSE}
# Attempt to melt covid to long format
covidGithubmelt <- melt(covidGithub, id = 1:11, variable.name = 'Date', variable.factor = FALSE,
                        value.name = 'Confirmed')
covidGithubmelt$Date <- as.Date(covidGithubmelt$Date, format = "%m/%d/%y")

# Current covid dates for each county
covidGithubmelt%>%
  group_by(county)%>%
  summarise(MinDate = min(Date), MaxDate = max(Date))%>%
  knitr::kable()

# Group by counties and order by date of dataset print out
covidGithubmelt <- covidGithubmelt%>%
  group_by(county)%>%
  arrange(Date, .by_group = TRUE)
```

```{r New Cases Varible, warning=FALSE}
# format the state variable
county_list <- unique(covidGithubmelt$county)
covidGithubmelt$county <- factor(covidGithubmelt$county, levels = county_list)

# Add variables for new_cases:
for (i in 1:length(county_list)) {
  cvd_subset = subset(covidGithubmelt, county == county_list[i])
  cvd_subset = cvd_subset[order(cvd_subset$Date),]

  # add starting level for new cases and deaths
  cvd_subset$new_cases = covidGithubmelt$Confirmed[1]

  for (j in 2:nrow(cvd_subset)) {
    cvd_subset$new_cases[j] =  cvd_subset$Confirmed[j] - cvd_subset$Confirmed[j-1] 
  }

  # include in main dataset
  covidGithubmelt$new_cases[covidGithubmelt$county == county_list[i]] = cvd_subset$new_cases
}
```

```{r COVID Visual by County}
p1<-ggplot(covidGithubmelt, aes(Date, new_cases, color = county))+
  geom_line()+
  geom_point(size = .5, alpha = 0.5)+
  labs(title = 'Incidences of Covid Cases in California by County', y = 'New cases', color = 'County')
ggplotly(p1)
p1<-NULL
```

```{r}
# FAILED attempt at county lables outside with color size being population estimate in 2015
###
# countypop <- countypop%>%
#   filter(abbr == 'CA')
# 
# coordinates <- covidGithubmelt%>%
#   select(county, FIPS, Long_, Lat)%>%
#   rename(fips = FIPS)%>%
#   unique()
# 
# countypop_cor <- cbind(coordinates[,2:4], countypop[, 2:4])
# 
# countypop_cor <- countypop_cor%>%
#   rename(lon = Long_, lat = Lat)%>%
#   mutate(lon=round(lat, 2), lat = round(lat, 2))%>%
#   relocate(lon, lat)
# 
# countypop_cor_t <- usmap_transform(countypop_cor)
# 
# plot_usmap(include = 'CA', fill = 'white', alpha = 0.25)+
#   ggrepel::geom_label_repel(data = countypop_cor_t,
#                             aes(x = lon.1, y = lat.1, label = county),
#                             size = 3, alpha = 0.8, label.r = unit(0.5, 'lines'), label.size = 0.5,
#                             segment.color = 'red', segment.size = 1, seed = 1002)+
#   geom_point(data = countypop_cor_t, aes(x = lon.1, y = lat.1, size = pop_2015),
#              color = 'purple', alpha = 0.5)+
#   scale_size_continuous(range = c(1,16), label = scales::comma)+
#   theme(legend.position = 'right')

```


```{r Spatial Visualization of COVID by County, warning=FALSE}
### Population in 2010 ###
cities_t <- usmap_transform(citypop)

plot_usmap(fill = 'white', alpha = 0.25)+
  ggrepel::geom_label_repel(data = cities_t,
                            aes(x = lon.1, y = lat.1, label = most_populous_city),
                            size = 3, alpha = 0.8, label.r = unit(0.5, 'lines'), label.size = 0.5,
                            segment.color = 'red', segment.size = 1, seed = 1002)+
  geom_point(data = cities_t, aes(x = lon.1, y = lat.1, size = city_pop),
             color = 'purple', alpha = 0.5)+
  scale_size_continuous(range = c(1,16), label = scales::comma)+
  labs(title = "Most Populous City in Each US State",
       subtitle = 'City Population in 2010 Census',
       size = 'City Population')+
  theme(legend.position = 'right')
###

plot_usmap("counties", include = 'CA', labels = TRUE, label_color = "blue", fill = "yellow",
           alpha = 0.25, color = "orange", size = 1)+
  labs(title = 'County Map of California')

# Adjusting Merge data set to ggmap setting with only FIPS and Confirmed variables 
mapdf <- covidGithubmelt%>%
  filter(Date == '2020-10-06')%>%
  select(FIPS, Confirmed)%>%
  distinct()%>%
  rename(fips = FIPS)

plot_usmap(data = mapdf, values='Confirmed', include = 'CA')+
  scale_fill_distiller(type = "seq", palette = "Spectral", direction = -1, name = "Confirmed Cases")+
  labs(title = 'Total Confirmed Cases in California by County',
       subtitle = 'Source: Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE)',
       caption = 'Up until 10/06/2020')+
  theme(plot.title = element_text(hjust = 0.5, vjust = 0.25, size = 18), legend.position = "right",
        legend.title = element_text(size = 14), legend.text = element_text(size = 12))
```


```{r, message=FALSE}
# Daily AQI for every county in California
csvAQI_data <- read_csv("data/ad_viz_plotval_data.csv")

csvAQI_data$Date <- as.Date(csvAQI_data$Date, format = "%m/%d/%Y")

# Test to see if counties have current dates
csvAQI_data%>%
  group_by(COUNTY)%>%
  summarise(MinDate = min(Date), MaxDate = max(Date))%>%
  knitr::kable()
```

```{r, warning=FALSE}
covidCounty <- unique(covidGithub$Admin2)
aqiCounty <- unique(csvAQI_data$COUNTY)

binary <- covidCounty %in% aqiCounty
matched <- intersect(covidCounty, aqiCounty)

df <- cbind(covidCounty, aqiCounty, binary)
knitr::kable(df, col.names = c('covidCounty', 'aqiCounty', 'Binary'))
knitr::kable(matched, col.names = 'Matched Counties')
```

### AQI Exploration

```{r}
# Renaming county code in AQI to FIPS to match with covid data set
csvAQI_data <- csvAQI_data%>%
  rename(FIPS = COUNTY_CODE, PM2.5 = `Daily Mean PM2.5 Concentration`)

csvAQI_data$FIPS <- paste0(6, csvAQI_data$FIPS)
csvAQI_data$FIPS <- as.numeric(csvAQI_data$FIPS)

csvAQI_data <- csvAQI_data[, c('Date', 'PM2.5', 'DAILY_AQI_VALUE', 'STATE', 'FIPS', 'COUNTY')]

# Renaming key variables in covid data set to merge with AQI
covidGithubmelt <- covidGithubmelt%>%
  rename(COUNTY = Admin2, STATE = Province_State, SITE_LATITUDE = Lat, SITE_LONGITUDE = Long_)

# To include geolocation of covid recording site
covidGithubmelt <- covidGithubmelt[, c('Date', 'FIPS', 'COUNTY', 'STATE',
                                       "SITE_LATITUDE", "SITE_LONGITUDE", 'Confirmed')]
```

```{r, message = FALSE, warning = FALSE}
# Is of merged data set when could be called earlier without AQI data, since no involvement in plot yet
# Visual map of California by county
# plot_usmap("counties", include = 'CA', labels = TRUE, label_color = "blue", fill = "yellow", alpha = 0.25,
#            color = "orange", size = 1)+
#   labs(title = 'County Map of California')
# 
# # Adjusting Merge data set to ggmap setting with only FIPS and Confirmed variables 
# mapdf <- covidGithubmelt%>%
#   filter(Date == '2020-10-06')%>%
#   select(FIPS, Confirmed)%>%
#   distinct()%>%
#   rename(fips = FIPS)
# 
# plot_usmap(data = mapdf, values='Confirmed', include = 'CA')+
#   scale_fill_distiller(type = "seq", palette = "Spectral", direction = -1, name = "Confirmed Cases")+
#   labs(title = 'Total Confirmed Cases in California by County',
#        subtitle = 'Source: Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE)',
#        caption = 'Up until 10/06/2020')+
#   theme(plot.title = element_text(hjust = 0.5, vjust = 0.25, size = 18), legend.position = "right",
#         legend.title = element_text(size = 14), legend.text = element_text(size = 12))
```

### Covid confirmed cases by county

```{r Merge of covid and AQI}
# Keeping the same matched couties in covid data set
covidGithubmelt <- covidGithubmelt[covidGithubmelt$COUNTY %in% matched, ]

# Full outer join
mergeFullOut <- merge(csvAQI_data, covidGithubmelt, all = TRUE)

# Deletes missing values for the first records of covid data in California appeared in 1/22/2020
mergeFullOut <- na.omit(mergeFullOut)
```

### Merge of Covid and AQI data sets

```{r EDA Merge}
# Could be in outout, but alos just mentioned of the extreme values for AQI and PM 2.5
mergeFullOut%>%
  group_by(COUNTY)%>%
  summarise(MinPM2.5 = min(PM2.5), MaxPM2.5 = max(PM2.5), MinAQI = min(DAILY_AQI_VALUE),
            MaxAQI = max(DAILY_AQI_VALUE))%>%
  knitr::kable()
```

### Summary of Merged data set

```{r}
# Line plot of daily covid cases in Los Angeles county
ggplot(mergeFullOut%>%
         filter(COUNTY == 'Los Angeles'), aes(x = Date, y = Confirmed))+
  geom_line()+
  labs(title = 'Daily covid cases in Los Angeles County', y = 'Confirmed Cases of Covid')

```

```{r}
# Line plot of daily AQI in Los Angeles county
ggplot(mergeFullOut%>%
         filter(COUNTY == 'Los Angeles'), aes(x = Date, y = DAILY_AQI_VALUE))+
  geom_line()+
  labs(title = 'Daily AQI in Los Angeles County', y = 'AQI')
```

### Visual Exploration

```{r Association test}
# Linear Regression to test the association between Confirmed covid cases and daily AQI
lm(Confirmed ~ DAILY_AQI_VALUE, data = mergeFullOut)%>%
  summary()
```

## Conclusion
